name: Verceel Production Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: |
          cd front-BES
          npm install -g vercel

      - name: Pull Vercel Environment Information
        run:  |
          cd front-BES
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run:  |
          cd front-BES
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run:  |
          cd front-BES
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}